### ISSUE TITLE
Null Exception

### ISSUE THREAD

**Issue by Nevin06** [sameer8saini/NZWalks#2]
**System.ArgumentNullException**
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 's')
  Source=System.Private.CoreLib
  StackTrace:
   at System.ArgumentNullException.Throw(String paramName)
   at System.Text.Encoding.GetBytes(String s)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__2(JwtBearerOptions options) in **_Program.cs:line 32_**
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

The **System.ArgumentNullException** occurs in the line mentioned below in Program.cs
```c#
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options => options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"],
        ValidAudience = builder.Configuration["Jwt:Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"]))
    });
``` 
<details><summary>Details</summary>
<p>

options.TokenValidationParameters.**ValidateIssuerSigningKey** is false
options.TokenValidationParameters.**ValidIssuer** is null
options.TokenValidationParameters.**ValidAudience** is null
options.TokenValidationParameters.**IssuerSigningKey** is  null

</p>
</details> 
@sameer8saini can you please fix the issue

**Comment by Nevin06** [comment]
Please find my repository here
[Null Exception](https://github.com/Nevin06/NZWalks/commit/b91eb0a128d119fbbf14f26e80421d9e12964579)

**Comment by Nevin06** [comment]
[Fix](https://www.udemy.com/course/build-rest-apis-with-aspnet-core-web-api-entity-framework/learn/lecture/31436186#questions/19429796/)
